# ============================================================
# app.marin.cr
# ============================================================

# --- HTTP (only for ACME + redirect) ---
server {
    listen 80;
    listen [::]:80;
    server_name app.marin.cr;

    # Allow Let's Encrypt HTTP-01 challenges
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    # Redirect everything else to HTTPS
    location / {
        return 301 https://$host$request_uri;
    }
}

# --- HTTPS ---
server {
    listen 443 ssl;
    listen [::]:443 ssl;
    http2 on;
	
    server_name app.marin.cr;
	
	# support big file uploads
	client_max_body_size 5g;

    ssl_certificate     /etc/letsencrypt/live/app.marin.cr/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/app.marin.cr/privkey.pem;

    location / {
        proxy_pass http://127.0.0.1:3021;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
    }
}

# ============================================================
# api.marin.cr
# ============================================================

# --- HTTP (only for ACME + redirect) ---
server {
    listen 80;
    listen [::]:80;
    server_name api.marin.cr;

    # Allow Let's Encrypt HTTP-01 challenges
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    # Redirect everything else to HTTPS
    location / {
        return 301 https://$host$request_uri;
    }
}

# --- HTTPS ---
server {
    listen 443 ssl;
    listen [::]:443 ssl;
    http2 on;
	
    server_name api.marin.cr;
	
	# support big file uploads
	client_max_body_size 5g;

    ssl_certificate     /etc/letsencrypt/live/api.marin.cr/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/api.marin.cr/privkey.pem;

    location / {
        proxy_pass http://127.0.0.1:5000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
    }
}
