server {
  listen 80;
  server_name proxy.marin.cr;

  location /.well-known/acme-challenge/ {
    root /var/www/certbot;
  }

  location / {
    return 301 https://$host$request_uri;
  }
}

server {
  listen 443 ssl;
  server_name proxy.marin.cr;

  ssl_certificate     /etc/letsencrypt/live/proxy.marin.cr/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/proxy.marin.cr/privkey.pem;

  location / {
    proxy_pass http://127.0.0.1:18080;

    # boringproxy needs the real host header
    proxy_set_header Host $host;

    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Real-IP $remote_addr;
  }
}