services:
  n8n:
    image: n8nio/n8n:latest
    container_name: infra-n8n
    restart: unless-stopped
    ports:
      - "127.0.0.1:5678:5678"
    env_file:
      - .env
    volumes:
      - ./data:/home/node/.n8n
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  default:
    name: proxy
    external: true