services:
  nextcloud:
    image: nextcloud:29-apache
    container_name: nextcloud
    restart: unless-stopped

    environment:
      NEXTCLOUD_ADMIN_USER: ${NEXTCLOUD_ADMIN_USER}
      NEXTCLOUD_ADMIN_PASSWORD: ${NEXTCLOUD_ADMIN_PASSWORD}

      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

      # S3_BUCKET: ${S3_BUCKET}
      # S3_KEY: ${S3_KEY}
      # S3_SECRET: ${S3_SECRET}
      # S3_REGION: ${S3_REGION}
      # S3_HOST: ${S3_HOST}
      # S3_USE_SSL: ${S3_USE_SSL}

      OBJECTSTORE_S3_BUCKET: ${OBJECTSTORE_S3_BUCKET}
      OBJECTSTORE_S3_KEY: ${OBJECTSTORE_S3_KEY}
      OBJECTSTORE_S3_SECRET: ${OBJECTSTORE_S3_SECRET}
      OBJECTSTORE_S3_REGION: ${OBJECTSTORE_S3_REGION}
      OBJECTSTORE_S3_HOST: ${OBJECTSTORE_S3_HOST}
      OBJECTSTORE_S3_SSL: ${OBJECTSTORE_S3_SSL}
      OBJECTSTORE_S3_PORT: ${OBJECTSTORE_S3_PORT}
      OBJECTSTORE_S3_AUTOCREATE: ${OBJECTSTORE_S3_AUTOCREATE}
      OBJECTSTORE_S3_PATHSTYLE: ${OBJECTSTORE_S3_PATHSTYLE}

      REDIS_HOST: ${REDIS_HOST}

    volumes:
      - ./data:/var/www/html

    networks:
      - proxy
      - internal

    ports:
      - "127.0.0.1:8082:80"

  redis:
    image: redis:7-alpine
    container_name: nextcloud-redis
    restart: unless-stopped
    networks:
      - internal

networks:
  proxy:
    external: true
  internal:
    internal: true
