services:
  postgres:
    image: pgvector/pgvector:pg17
    container_name: infra-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    command: >
      postgres
      -c listen_addresses=*
      -c password_encryption=scram-sha-256
      -c log_line_prefix='%m [%p] [%h] '
      -c log_connections=on
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - internal

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: infra-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "127.0.0.1:5050:80"
    networks:
      - internal
      - proxy

networks:
  internal:
    driver: bridge
  proxy:
    external: true

volumes:
  pgadmin_data:
